# Generated by Django 2.2.14 on 2021-03-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('peliculas', '0001_initial'),
        ('series_pagadas', '0001_initial'),
        ('series', '0001_initial'),
        ('categorias', '0001_initial'),
        ('peliculas_pagadas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Category', models.ManyToManyField(related_name='Espacio', to='categorias.Categoria')),
                ('movie', models.ManyToManyField(related_name='Espacio', to='peliculas.Pelicula')),
                ('paid_movie', models.ManyToManyField(related_name='Espacio', to='peliculas_pagadas.Pelicula_pagada')),
                ('paid_series', models.ManyToManyField(related_name='Espacio', to='series_pagadas.Serie_pagada')),
                ('series', models.ManyToManyField(related_name='Espacio', to='series.Serie')),
            ],
        ),
    ]
