# Generated by Django 2.2.14 on 2021-03-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('peliculas', '0001_initial'),
        ('peliculas_pagadas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('movies', models.ManyToManyField(related_name='Categoria', to='peliculas.Pelicula')),
                ('paid_movies', models.ManyToManyField(related_name='Categoria', to='peliculas_pagadas.Pelicula_pagada')),
            ],
        ),
    ]
